events {
    worker_connections 256;
}

http {
    client_max_body_size 50M;

    server {
        listen 80;

        location / {
            proxy_pass http://flask:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 120s;
        }
    }
}
